apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: account-balance
data:
  application-k8s.yml: |
    server:
      port: 8080
    
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://host.docker.internal:3306/VTMSystem?useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          
      data:
        redis:
          host: host.docker.internal
          port: 6379
          password: 123456
          timeout: 5000
          
    logging:
      level:
        org.springframework: INFO
        com.kevinbank: DEBUG
