spring:
  main:
    allow-circular-references: true

  data:
    redis:
      host: r-bp1zj7w1xeu1nkco17pd.redis.rds.aliyuncs.com
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        pool:
          max-active: 8  # 最大连接数
          max-wait: -1   # 最大阻塞等待时间
          max-idle: 8    # 最大空闲连接
          min-idle: 0    # 最小空闲连接
      username: kevin
      password: Zaq12wsx@22

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}