apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: accountbalancecalculation
data:
  application.yml: |
    spring:
      application:
        name: AccountBalanceCalculationApplication
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          maximum-pool-size: 50
          minimum-idle: 10
          connection-timeout: 30000
      data:
        redis:
          database: 0
          timeout: 60000
          lettuce:
            pool:
              max-active: 20
              max-idle: 10
              min-idle: 5
    
    server:
      port: 8080
      
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE 