apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: account-balance-app-hpa
  namespace: account-balance
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: account-balance-app
  minReplicas: 2
  maxReplicas: 4  # 最大副本数
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # CPU 目标使用率
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 缩容稳定窗口
