apiVersion: v1
kind: Service
metadata:
  name: account-balance-app
  namespace: account-balance
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    app: account-balance-app

